In [1]:
import numpy as np

# Employee Dataset
X = np.array([
    [22, 25000, 1],
    [25, 30000, 2],
    [30, 50000, 5],
    [35, 70000, 8],
    [40, 90000, 12]
])

print("Dataset:")
print(X)

print("\nEmployees with Salary > 50000")
print(X[X[:, 1] > 50000])

print("\nEmployees with Experience >= 5")
print(X[X[:, 2] >= 5])

print("\nSalary > 30000 AND Experience >= 5")
print(X[(X[:, 1] > 30000) & (X[:, 2] >= 5)])

print("\nSalary < 30000 OR Experience > 10")
print(X[(X[:, 1] < 30000) | (X[:, 2] > 10)])

print("\nFancy Indexing")
print(X[[0, 2, 4]])

Dataset:
[[   22 25000     1]
 [   25 30000     2]
 [   30 50000     5]
 [   35 70000     8]
 [   40 90000    12]]

Employees with Salary > 50000
[[   35 70000     8]
 [   40 90000    12]]

Employees with Experience >= 5
[[   30 50000     5]
 [   35 70000     8]
 [   40 90000    12]]

Salary > 30000 AND Experience >= 5
[[   30 50000     5]
 [   35 70000     8]
 [   40 90000    12]]

Salary < 30000 OR Experience > 10
[[   22 25000     1]
 [   40 90000    12]]

Fancy Indexing
[[   22 25000     1]
 [   30 50000     5]
 [   40 90000    12]]
