In [1]:
import numpy as np

X = np.array([
    [22, 25000, 1],
    [25, 30000, 2],
    [30, 50000, 5],
    [35, 70000, 8],
    [40, 90000, 12]
])

# 1
print(X[0])

# 2
print(X[-1])

# 3
print(X[:, 1])

# 4
print(X[:, 2])

# 5
print(X[:3])

# 6
print(X[-2:])

# 7
print(X[:, 0:2])

# 8
print(X[1:4, 0:2])

# 9
print(X[3, 1])

# 10
print(X[-1, 2])

[   22 25000     1]
[   40 90000    12]
[25000 30000 50000 70000 90000]
[ 1  2  5  8 12]
[[   22 25000     1]
 [   25 30000     2]
 [   30 50000     5]]
[[   35 70000     8]
 [   40 90000    12]]
[[   22 25000]
 [   25 30000]
 [   30 50000]
 [   35 70000]
 [   40 90000]]
[[   25 30000]
 [   30 50000]
 [   35 70000]]
70000
12
