In [1]:
import numpy as np

X = np.array([
    [22, 25000, 1],
    [25, 30000, 2],
    [30, 50000, 5],
    [35, 70000, 8],
    [40, 90000, 12]
])

print("Dataset:")
print(X)

print("\nFirst row:")
print(X[0])

print("\nLast row:")
print(X[-1])

print("\nSalary column:")
print(X[:, 1])

print("\nExperience column:")
print(X[:, 2])

print("\nFirst 3 rows:")
print(X[0:3])

print("\nLast 2 rows:")
print(X[-2:])

print("\nAge and Salary Columns:")
print(X[:, 0:2])

Dataset:
[[   22 25000     1]
 [   25 30000     2]
 [   30 50000     5]
 [   35 70000     8]
 [   40 90000    12]]

First row:
[   22 25000     1]

Last row:
[   40 90000    12]

Salary column:
[25000 30000 50000 70000 90000]

Experience column:
[ 1  2  5  8 12]

First 3 rows:
[[   22 25000     1]
 [   25 30000     2]
 [   30 50000     5]]

Last 2 rows:
[[   35 70000     8]
 [   40 90000    12]]

Age and Salary Columns:
[[   22 25000]
 [   25 30000]
 [   30 50000]
 [   35 70000]
 [   40 90000]]
