In [2]:
import numpy as np

# Python List
numbers = [1, 2, 3, 4, 5]

# NumPy Array
arr = np.array([1, 2, 3, 4, 5])

print(type(numbers))
print(type(arr))

# Vectorization
print(arr * 2)

# 2D Array
X = np.array([
    [25, 30000, 2],
    [30, 50000, 5],
    [35, 70000, 8]
])

print(X)
print(X.shape)

<class 'list'>
<class 'numpy.ndarray'>
[ 2  4  6  8 10]
[[   25 30000     2]
 [   30 50000     5]
 [   35 70000     8]]
(3, 3)
