In [1]:
import numpy as np
x = np.array([
    [22, 25000, 1],
    [25, 30000, 2],
    [30, 50000, 5],
    [35, 70000, 8],
    [40, 90000, 12]
])
print("Shape:", x.shape)
print("No of Dimensions:", x.ndim)
print("Data Type:", x.dtype)
x[:, 1] = x[:, 1] + 5000
x[:, 2] = x[:, 2] + 1
print("Updated Dataset:\n", x)  
print("Total memory consumed by the array:", x.nbytes, "bytes")
salary_per_experience = x[:, 1] / x[:, 2]
print("\nSalary per experience:")
print(salary_per_experience)

Shape: (5, 3)
No of Dimensions: 2
Data Type: int64
Updated Dataset:
 [[   22 30000     2]
 [   25 35000     3]
 [   30 55000     6]
 [   35 75000     9]
 [   40 95000    13]]
Total memory consumed by the array: 120 bytes

Salary per experience:
[15000.         11666.66666667  9166.66666667  8333.33333333
  7307.69230769]
