In [1]:
import numpy as np

employee_data = np.array([
    [22,25000,1],
    [25,30000,2],
    [30,50000,5],
    [35,70000,8],
    [40,90000,12]
])

print("Dataset:")
print(employee_data)

print("\nShape:")
print(employee_data.shape)

print("\nDimensions:")
print(employee_data.ndim)

print("\nTotal Elements:")
print(employee_data.size)

print("\nDatatype:")
print(employee_data.dtype)

print("\nMemory Usage:")
print(employee_data.nbytes, "bytes")

Dataset:
[[   22 25000     1]
 [   25 30000     2]
 [   30 50000     5]
 [   35 70000     8]
 [   40 90000    12]]

Shape:
(5, 3)

Dimensions:
2

Total Elements:
15

Datatype:
int64

Memory Usage:
120 bytes
