In [1]:
import numpy as np

# 1D Array
arr1 = np.array([10, 20, 30, 40])

print("1D Array:")
print(arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)

# 2D Array
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("\n2D Array:")
print(arr2)
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)

# 3D Array
arr3 = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print("\n3D Array:")
print(arr3)
print("Shape:", arr3.shape)
print("Dimensions:", arr3.ndim)

1D Array:
[10 20 30 40]
Shape: (4,)
Dimensions: 1

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3
