Tasks
1. Convert into shape (4,6)
2. Convert into shape (6,4)
3. Print total elements
4. Print dimensions
5. Flatten the array
6. Transpose the (4,6) array
7. Print transpose shape
8. Create a (2,3,4) array
9. Flatten the (2,3,4) array
10. Verify total elements remain unchanged

❌ No loops allowed


In [8]:
import numpy as np

X = np.arange(1,25)

#1
reshaped_4X6 = X.reshape(4, 6)
print("4X6 array:")
print(reshaped_4X6)

#2
reshaped_6X4 = X.reshape(6, 4)
print("\n6X4 array:")
print(reshaped_6X4)

#3
print("\nTotal elements:")
print(X.size)

#4
print("\nDimensions:")
print(reshaped_4X6.ndim)

#5 
flat = reshaped_4X6.flatten()
print("\nFlattened array:")
print(flat)

#6 
transposed = reshaped_4X6.T
print("\nTransposed array:")
print(transposed)

#7
print("\nTransposed shape:")
print(transposed.shape)

#8
reshaped_2X3X4 = X.reshape(2, 3, 4)
print("\n2X3X4 array:")
print(reshaped_2X3X4)

#9
flat_2X3X4 = reshaped_2X3X4.flatten()
print("\nFlattened 2X3X4 array:")
print(flat_2X3X4)

#10
print("\nOriginal shape:", reshaped_2X3X4.shape)
print("\nFlattened shape:", flat_2X3X4.shape)
print("\nVerification:", flat_2X3X4.size == reshaped_2X3X4.size)

4X6 array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

6X4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Total elements:
24

Dimensions:
2

Flattened array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Transposed array:
[[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]

Transposed shape:
(6, 4)

2X3X4 array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Flattened 2X3X4 array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Original shape: (2, 3, 4)

Flattened shape: (24,)

Verification: True
