In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])

print("Original array:", arr)

reshaped = arr.reshape(2, 3)

print("\nReshaped array :")
print(reshaped)

print("\nShape :")
print(reshaped.shape)

flat = reshaped.flatten()

print("\nFlattened array:")
print(flat)

transposed = reshaped.T
print("\nTransposed array:")
print(transposed)

print("\nTransposed shape:")
print(transposed.shape)

Original array: [1 2 3 4 5 6]

Reshaped array :
[[1 2 3]
 [4 5 6]]

Shape :
(2, 3)

Flattened array:
[1 2 3 4 5 6]
